# Generated by Django 3.1.5 on 2021-02-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates wheter the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
