# Generated by Django 3.1.6 on 2021-04-14 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210413_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followees',
            field=models.ManyToManyField(blank=True, related_name='user_followees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
