# Generated by Django 3.1.6 on 2021-05-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_auto_20210325_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='postapp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='投稿画像'),
        ),
    ]
