# Generated by Django 3.1.6 on 2021-05-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0005_postapp_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postapp',
            name='image',
        ),
        migrations.AddField(
            model_name='postapp',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='投稿画像1'),
        ),
        migrations.AddField(
            model_name='postapp',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='投稿画像2'),
        ),
        migrations.AddField(
            model_name='postapp',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='投稿画像3'),
        ),
    ]
