# Generated by Django 3.1.6 on 2021-05-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_postapp_map_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postapp',
            name='map_info',
        ),
        migrations.AddField(
            model_name='postapp',
            name='map_addrs',
            field=models.CharField(max_length=30, null=True, verbose_name='地図住所'),
        ),
    ]
